Repository cse210-fa24-group14/cse210-fa24-group14, pull requests merged in 2024-12, with the labels that each got.

#47 feat: setup jsdocs
  .eslintrc.json
  .husky/pre-commit
  jsdoc.json
  package-lock.json
  package.json
  scripts/generateJSDoc.js
Labels: enhancement

#46 feat: markdown support
  package-lock.json
  package.json
  src/entry.html
  src/js/components/NotesView.js
  src/js/utils.js
  src/styles/stylesheet.css
  tests/unit/Utils.test.js
Labels: enhancement

#66 feat: code editor details
  src/js/components/NotesView.js
  src/js/components/SyntaxHighlighter.js
  src/styles/stylesheet.css
Labels: enhancement

#71 feat: use indexDB
  src/js/repositories/NoteRepository.js
  src/js/services/IndexDBService.js
  src/js/services/StorageService.js
  tests/unit/NotesRepository.test.js
Labels: bug

#99 docs: Update README.md to add Privacy Policy for CWS deployment
  README.md
Labels: documentation
