Repository cse210-fa24-group14/cse210-fa24-group14, pull requests merged in 2024-11, with the labels that each got.

#9 Feature 005 - Unit and E2E Test Support for Chrome Extensions with PlayWright
  .gitignore
  background.js
  index.html
  index.js
  manifest.json
  package-lock.json
  package.json
  playwright.config.js
  playwright/fixtures.js
  styles.css
  tests/e2e/index.e2e.test.js
  tests/unit/index.test.js
Labels: good first issue

#13 feat(test): Add CI pipelines and make targets
  .github/workflow/check.lint-title.yaml
  .github/workflow/ci.tests.yaml
  Makefile
  playwright/fixtures.js
  tests/e2e/basicButton.test.js
  tests/unit/basicButton.test.js
Labels: enhancement, test

#14 fix: fix workflows folder name
  .github/workflows/check.lint-title.yaml
  .github/workflows/ci.tests.yaml
Labels: bug, test

#7 feat: add chrome extension for Dev Diary
  .github/workflows/ci.tests.yaml
  README.md
  eslint.config.mjs
  index.html
  index.js
  manifest.json
  playwright.config.js
  src/assets/dev_diary.png
  src/entry.html
  src/js/background.js
  src/js/displayNotes.js
  src/js/entry.js
  src/js/saveNotes.js
  src/js/utils.js
  src/styles/stylesheet.css
  styles.css
  tests/e2e/basicButton.test.js
  tests/e2e/entry.e2e.test.js
  tests/unit/basicButton.test.js
  tests/unit/displayNotes.test.js
  tests/unit/saveNotes.test.js
Labels: enhancement, template

#24 chore: Create Issue Templates
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: template

#29 chore: Create pull_request_template.md
  .github/pull_request_template.md
Labels: template

#26 chore: Update 111924-sprint-planning-2.md
  admin/meetings/111924-sprint-planning-2.md
Labels: documentation

#34 ci: add pre commit hook for commit message check
  .husky/commit-msg
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement, test

#37 docs: update meeting logs for 112224 progress checkin
  admin/meetings/112224-progress-checkin.md
Labels: documentation

#38 docs: Update 112224-progress-checkin.md
  admin/meetings/112224-progress-checkin.md
Labels: documentation

#41 refactor: modularize codebase to make more clear structure
  .gitignore
  src/js/components/NoteListView.js
  src/js/displayNotes.js
  src/js/entry.js
  src/js/models/Note.js
  src/js/repositories/NoteRepository.js
  src/js/saveNotes.js
  src/js/services/StorageService.js
  src/js/utils.js
  tests/e2e/entry.e2e.test.js
  tests/unit/displayNotes.test.js
  tests/unit/saveNotes.test.js
Labels: enhancement

#49 chore: sprint 3 meeting notes
  admin/meetings/112524-sprint3-planning.md
Labels: documentation
